export const NEW_PLEDGE = 'NEW_PLEDGE';
export const NEW_PLEDGE_FAIL = 'NEW_PLEDGE_FAIL';
export const CANCEL_PLEDGE = 'CANCEL_PLEDGE';
export const CANCEL_PLEDGE_FAIL = 'CANCEL_PLEDGE_FAIL';
export const GOT_PLEDGE = 'GOT_PLEDGE';
export const GET_PLEDGE_FAIL = 'GET_PLEDGE_FAIL';
