#!/bin/bash

# run production mode
export NODE_ENV="production"
#export GRAPHENEDB_URL="https://neo_asa_miller_gold:gtdyZGz3qsVWoWFkLOgpne43N5QMTJYg0O871FoZ@neo-asa-miller-gold.aws.graphstory.com:7473/"
# export MANDRILL_API_KEY="MFilFuy2hIkok1JpDF5JVQ"
# export S3_BUCKET="raiserve-images-production"
# export S3_ACCESS_KEY_ID="AKIAJ7VODXA6DNBCPFIQ"
# export S3_SECRET_ACCESS_KEY="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"
# export STRIPE_SECRET_KEY="sk_test_VxrSBOOWOiUa2FVSDSCgZ0RX"
# export STRIPE_PUBLISHABLE_KEY="pk_test_qLwGpc6OnsFiIc8D8XF3cy2G"
npm start
