export const HOUR_LOG_ON_SUCCESS = 'HOUR_LOG_ON_SUCCESS';
export const HOUR_LOG_ON_FAIL = 'HOUR_LOG_ON_FAIL';
export const VOLUNTEER = 'VOLUNTEER';
export const VOLUNTEER_ERROR = 'VOLUNTEER_ERROR';
export const VOLUNTEERS = 'VOLUNTEERS';
export const VOLUNTEERS_ERROR = 'VOLUNTEERS_ERROR';
