export const NEW_PROJECT = 'NEW_PROJECT';
export const NEW_PROJECT_FAIL = 'NEW_PROJECT_FAIL';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';
export const LIST_PROJECTS = 'LIST_PROJECTS';
export const LIST_PROJECTS_FAIL = 'LIST_PROJECTS_FAIL';
export const GET_HOURS = 'GET_HOURS';
