export const NEW_PROJECT = 'NEW_PROJECT';
export const NEW_PROJECT_FAIL = 'NEW_PROJECT_FAIL';
export const INDEX_PROJECTS = 'INDEX_PROJECTS';
export const INDEX_PROJECTS_FAIL = 'INDEX_PROJECTS_FAIL';
