export const INVITE_USER = 'INVITE_USER';
export const INVITE_FAILED = 'INVITE_FAILED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST_FAILED = 'RESET_PASSWORD_REQUEST_FAILED';
export const RESET_USER_REDUX = 'RESET_USER_REDUX';
